name: Manual-Maven-Central-Sync

on:
  workflow_dispatch:
    inputs:
      project_version:
        description: 'Project version (e.g, v1.2.3) - Make sure this version is already published to Bintray'
        required: true

jobs:
  # NOTE: Do not sync multiple repos to Maven Central in parallel. It's unsupported so will fail.
  publish_maven:
    if: (github.repository == 'hedgehogqa/scala-hedgehog') && startsWith(github.event.inputs.project_version, 'v')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync to Maven Central
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          export GITHUB_TAG=${{ github.event.inputs.project_version }}
          .github/workflows/maven_central_sync.sh
